local rs = game.ReplicatedStorage
rs.SpawnGalaxyBlock:FireServer()
task.wait(0.1)
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
rs.SpawnGalaxyBlock:FireServer()
